<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::connection('main')->table('users')->insert([
            // Koordinator
            [
                'name' => 'Koordinator PWK',
                'email' => 'koordinator@pwk.com',
                'nomor_induk' => 'KD6001',
                'password' => Hash::make('password'),
                'first_login' => false,
                'is_active' => true,
                'study_program_id' => 1,
                'created_at' => now(),
            ],
            [
                'name' => 'Koordinator Elektro',
                'email' => 'koordinator@elektro.com',
                'nomor_induk' => 'KD7001',
                'password' => Hash::make('password'),
                'first_login' => false,
                'is_active' => true,
                'study_program_id' => 2,
                'created_at' => now(),
            ],

            // Admin
            [
                'name' => 'Admin PWK',
                'email' => 'admin@pwk.com',
                'nomor_induk' => 'ADM6001',
                'password' => Hash::make('password'),
                'first_login' => false,
                'is_active' => true,
                'study_program_id' => 1,
                'created_at' => now(),
            ],
            [
                'name' => 'Admin Elektro',
                'email' => 'admin@elektro.com',
                'nomor_induk' => 'ADM7001',
                'password' => Hash::make('password'),
                'first_login' => false,
                'is_active' => true,
                'study_program_id' => 2,
                'created_at' => now(),
            ],

            // Dosen
            [
                'name' => 'Dosen PWK',
                'email' => 'dosen@pwk.com',
                'nomor_induk' => 'DSN6001',
                'password' => Hash::make('password'),
                'first_login' => false,
                'is_active' => true,
                'study_program_id' => 1,
                'created_at' => now(),
            ],
            [
                'name' => 'Dosen 2 PWK',
                'email' => 'dosen2@pwk.com',
                'nomor_induk' => 'DSN6002',
                'password' => Hash::make('password'),
                'first_login' => false,
                'is_active' => true,
                'study_program_id' => 1,
                'created_at' => now(),
            ],
            [
                'name' => 'Dosen Elektro',
                'email' => 'dosen@elektro.com',
                'nomor_induk' => 'DSN7001',
                'password' => Hash::make('password'),
                'first_login' => false,
                'is_active' => true,
                'study_program_id' => 2,
                'created_at' => now(),
            ],
            [
                'name' => 'Dosen 2 Elektro',
                'email' => 'dosen2@elektro.com',
                'nomor_induk' => 'DSN7002',
                'password' => Hash::make('password'),
                'first_login' => false,
                'is_active' => true,
                'study_program_id' => 2,
                'created_at' => now(),
            ],

            // Mahasiswa
            [
                'name' => 'Mahasiswa PWK',
                'email' => 'mahasiswa@pwk.com',
                'nomor_induk' => 'MHS6001',
                'password' => Hash::make('password'),
                'first_login' => false,
                'is_active' => true,
                'study_program_id' => 1,
                'created_at' => now(),
            ],
            [
                'name' => 'Mahasiswa 2PWK',
                'email' => 'mahasiswa2@pwk.com',
                'nomor_induk' => 'MHS6002',
                'password' => Hash::make('password'),
                'first_login' => false,
                'is_active' => true,
                'study_program_id' => 1,
                'created_at' => now(),
            ],
            [
                'name' => 'Mahasiswa 3PWK',
                'email' => 'mahasiswa3@pwk.com',
                'nomor_induk' => 'MHS6003',
                'password' => Hash::make('password'),
                'first_login' => false,
                'is_active' => true,
                'study_program_id' => 1,
                'created_at' => now(),
            ],
                        [
                'name' => 'Mahasiswa 4PWK',
                'email' => 'mahasiswa4@pwk.com',
                'nomor_induk' => 'MHS6004',
                'password' => Hash::make('password'),
                'first_login' => false,
                'is_active' => true,
                'study_program_id' => 1,
                'created_at' => now(),
            ],
            [
                'name' => 'Mahasiswa 5PWK',
                'email' => 'mahasiswa5@pwk.com',
                'nomor_induk' => 'MHS6005',
                'password' => Hash::make('password'),
                'first_login' => false,
                'is_active' => true,
                'study_program_id' => 1,
                'created_at' => now(),
            ],
            [
                'name' => 'Mahasiswa 6PWK',
                'email' => 'mahasiswa6@pwk.com',
                'nomor_induk' => 'MHS6006',
                'password' => Hash::make('password'),
                'first_login' => false,
                'is_active' => true,
                'study_program_id' => 1,
                'created_at' => now(),
            ],
            [
                'name' => 'Mahasiswa 7PWK',
                'email' => 'mahasiswa7@pwk.com',
                'nomor_induk' => 'MHS6007',
                'password' => Hash::make('password'),
                'first_login' => false,
                'is_active' => true,
                'study_program_id' => 1,
                'created_at' => now(),
            ],
                        [
                'name' => 'Mahasiswa 8PWK',
                'email' => 'mahasiswa8@pwk.com',
                'nomor_induk' => 'MHS6008',
                'password' => Hash::make('password'),
                'first_login' => false,
                'is_active' => true,
                'study_program_id' => 1,
                'created_at' => now(),
            ],
            [
                'name' => 'Mahasiswa 9PWK',
                'email' => 'mahasiswa9@pwk.com',
                'nomor_induk' => 'MHS6009',
                'password' => Hash::make('password'),
                'first_login' => false,
                'is_active' => true,
                'study_program_id' => 1,
                'created_at' => now(),
            ],
            [
                'name' => 'Mahasiswa 10PWK',
                'email' => 'mahasiswa10@pwk.com',
                'nomor_induk' => 'MHS60010',
                'password' => Hash::make('password'),
                'first_login' => false,
                'is_active' => true,
                'study_program_id' => 1,
                'created_at' => now(),
            ],
            [
                'name' => 'Mahasiswa Elektro',
                'email' => 'mahasiswa@elektro.com',
                'nomor_induk' => 'MHS7001',
                'password' => Hash::make('password'),
                'first_login' => false,
                'is_active' => true,
                'study_program_id' => 2,
                'created_at' => now(),
            ],
            [
                'name' => 'Mahasiswa 2Elektro',
                'email' => 'mahasiswa2@elektro.com',
                'nomor_induk' => 'MHS7002',
                'password' => Hash::make('password'),
                'first_login' => false,
                'is_active' => true,
                'study_program_id' => 2,
                'created_at' => now(),
            ],
            [
                'name' => 'Mahasiswa 3Elektro',
                'email' => 'mahasiswa3@elektro.com',
                'nomor_induk' => 'MHS7003',
                'password' => Hash::make('password'),
                'first_login' => false,
                'is_active' => true,
                'study_program_id' => 2,
                'created_at' => now(),
            ],
            [
                'name' => 'Mahasiswa 4Elektro',
                'email' => 'mahasiswa4@elektro.com',
                'nomor_induk' => 'MHS7004',
                'password' => Hash::make('password'),
                'first_login' => false,
                'is_active' => true,
                'study_program_id' => 2,
                'created_at' => now(),
            ],
            [
                'name' => 'Mahasiswa 5Elektro',
                'email' => 'mahasiswa5@elektro.com',
                'nomor_induk' => 'MHS7005',
                'password' => Hash::make('password'),
                'first_login' => false,
                'is_active' => true,
                'study_program_id' => 2,
                'created_at' => now(),
            ],
            [
                'name' => 'Mahasiswa 6Elektro',
                'email' => 'mahasiswa6@elektro.com',
                'nomor_induk' => 'MHS7006',
                'password' => Hash::make('password'),
                'first_login' => false,
                'is_active' => true,
                'study_program_id' => 2,
                'created_at' => now(),
            ],
            [
                'name' => 'Mahasiswa 7Elektro',
                'email' => 'mahasiswa7@elektro.com',
                'nomor_induk' => 'MHS7007',
                'password' => Hash::make('password'),
                'first_login' => false,
                'is_active' => true,
                'study_program_id' => 2,
                'created_at' => now(),
            ],
            [
                'name' => 'Mahasiswa 8Elektro',
                'email' => 'mahasiswa8@elektro.com',
                'nomor_induk' => 'MHS7008',
                'password' => Hash::make('password'),
                'first_login' => false,
                'is_active' => true,
                'study_program_id' => 2,
                'created_at' => now(),
            ],

            [
                'name' => 'Mahasiswa 9Elektro',
                'email' => 'mahasiswa9@elektro.com',
                'nomor_induk' => 'MHS7009',
                'password' => Hash::make('password'),
                'first_login' => false,
                'is_active' => true,
                'study_program_id' => 2,
                'created_at' => now(),
            ],

            [
                'name' => 'Mahasiswa 10Elektro',
                'email' => 'mahasiswa10@elektro.com',
                'nomor_induk' => 'MHS70010',
                'password' => Hash::make('password'),
                'first_login' => false,
                'is_active' => true,
                'study_program_id' => 2,
                'created_at' => now(),
            ],
        ]);

    }
}
